"""Disclosure report rendering for CSRD (ESRS E1) and SEC (Reg S-K Item 1504/1505).

The quantitative sections are rendered from the ledger by code. The narrative section
comes from the Disclosure Writer agent when available, otherwise from the template here.
Both paths use the identical figures payload.
"""
from __future__ import annotations

from collections import Counter
from decimal import Decimal
from typing import Any

from ..factors.matcher import ACTIVITY_TYPES
from ..schemas import AgentLogEntry, LedgerEntry, RunSummary

SCOPE3_CATEGORY_NAMES = {
    1: "Purchased goods and services", 2: "Capital goods", 3: "Fuel- and energy-related activities",
    4: "Upstream transportation and distribution", 5: "Waste generated in operations", 6: "Business travel",
    7: "Employee commuting", 8: "Upstream leased assets", 9: "Downstream transportation", 10: "Processing of sold products",
    11: "Use of sold products", 12: "End-of-life treatment", 13: "Downstream leased assets", 14: "Franchises", 15: "Investments",
}

JURISDICTIONS = {
    "CSRD": {"label": "EU CSRD / ESRS E1", "ghg_ref": "ESRS E1-6", "energy_ref": "ESRS E1-5", "assurance": "limited assurance under CSRD Art. 34, moving to reasonable assurance"},
    "SEC": {"label": "US SEC Climate Disclosure (Reg S-K)", "ghg_ref": "Item 1504", "energy_ref": "Item 1502", "assurance": "attestation under Item 1505 (limited, then reasonable assurance for LAFs)"},
}


def figures_payload(run: RunSummary, entries: list[LedgerEntry], jurisdiction: str) -> dict[str, Any]:
    t = run.totals
    sources = sorted({e.factor_match.factor.source.split(",")[0].split(" (")[0] for e in entries if e.factor_match.factor})
    gwps = sorted({e.factor_match.factor.gwp_set for e in entries if e.factor_match.factor and e.factor_match.factor.gwp_set})
    spend_share = (t.spend_based_t / t.total_location_based) if t.total_location_based > 0 else Decimal("0")
    return {
        "jurisdiction": jurisdiction,
        "org_name": run.org_name,
        "reporting_period": run.reporting_period,
        "figures": {
            "scope1_t": str(t.scope1),
            "scope2_location_t": str(t.scope2_location),
            "scope3_t": str(t.scope3),
            "total_location_based_t": str(t.total_location_based),
            "scope3_by_category": {k: str(v) for k, v in t.scope3_by_category.items()},
            "by_activity": {k: str(v) for k, v in t.by_activity.items()},
        },
        "methodology": {
            "standard": "GHG Protocol Corporate Accounting and Reporting Standard",
            "scope2_method": "location-based",
            "gwp_set": ", ".join(gwps) or "AR5-100 (factor tables pre-weighted)",
            "factor_sources": sources,
            "arithmetic": "python.decimal (28-digit), tool-computed, per-line lineage",
        },
        "findings": [f.model_dump() for f in run.findings],
        "data_quality": {
            "lines_total": t.lines_total,
            "lines_calculated": t.lines_calculated,
            "lines_unmatched": t.lines_unmatched,
            "lines_unclassified": t.lines_unclassified,
            "lines_excluded": t.lines_excluded,
            "spend_based_share": str(spend_share.quantize(Decimal("0.0001"))),
        },
        "offsets_t": "0",
    }


def template_narrative(p: dict[str, Any]) -> str:
    j = JURISDICTIONS.get(p["jurisdiction"], JURISDICTIONS["CSRD"])
    f = p["figures"]
    m = p["methodology"]
    dq = p["data_quality"]
    findings = p.get("findings", [])
    lines = [
        "## Basis of preparation",
        f"{p['org_name']} reports greenhouse gas emissions for {p['reporting_period']} under the {j['label']} framework, "
        f"prepared in accordance with the {m['standard']}. Scope 2 is reported on a {m['scope2_method']} basis. "
        f"Emission factors are taken from {', '.join(m['factor_sources']) or 'the bundled official tables'} using the {m['gwp_set']} global warming potentials. "
        f"All arithmetic was performed by deterministic tooling ({m['arithmetic']}); no figure in this disclosure was generated by a language model.",
        "",
        f"## GHG emissions ({j['ghg_ref']})",
        f"Gross Scope 1 emissions were {f['scope1_t']} tCO2e. Gross location-based Scope 2 emissions were {f['scope2_location_t']} tCO2e. "
        f"Gross Scope 3 emissions were {f['scope3_t']} tCO2e. Total gross location-based emissions were {f['total_location_based_t']} tCO2e.",
    ]
    if f["scope3_by_category"]:
        lines.append("Scope 3 by GHG Protocol category:")
        for cat, val in sorted(f["scope3_by_category"].items(), key=lambda kv: int(kv[0])):
            lines.append(f"- Category {cat}, {SCOPE3_CATEGORY_NAMES.get(int(cat), 'Other')}: {val} tCO2e")
    lines += [
        "",
        "## Data quality and limitations",
        f"Of {dq['lines_total']} source lines, {dq['lines_calculated']} were calculated, {dq['lines_unmatched']} had no official factor in the requested region and were excluded rather than estimated, "
        f"{dq['lines_unclassified']} could not be classified and await manual review, and {dq['lines_excluded']} were identified as non-emission items. "
        f"The share of the total derived from spend-based (EEIO) factors is {dq['spend_based_share']}.",
    ]
    if findings:
        lines.append("Control findings raised during preparation:")
        for fd in findings:
            lines.append(f"- [{fd['severity'].upper()}] {fd['check_id']} {fd['title']}: {fd['detail']}")
    else:
        lines.append("No control findings were raised during preparation.")
    lines += [
        "",
        "## Governance and assurance readiness",
        f"Every figure above links to a ledger line carrying the source document reference, the redacted source text, the classification rule or agent decision, the factor row citation, unit conversion constants and the full formula. "
        f"This lineage is retained to support {j['assurance']}. This disclosure reports gross emissions only and makes no neutrality claim and no use of purchased credits.",
    ]
    return "\n".join(lines)


def render_markdown(run: RunSummary, entries: list[LedgerEntry], log: list[AgentLogEntry], narrative: str, narrative_source: str, jurisdiction: str) -> str:
    j = JURISDICTIONS.get(jurisdiction, JURISDICTIONS["CSRD"])
    t = run.totals
    out: list[str] = []
    out.append(f"# {run.org_name} — GHG Emissions Disclosure {run.reporting_period}")
    out.append(f"*Framework: {j['label']} · Run {run.run_id} · Generated {run.created_at} · Narrative source: {narrative_source}*")
    out.append("")
    if not run.report_allowed:
        out.append("> **REPORT BLOCKED.** Blocking findings are open. This document is a draft for remediation and must not be filed.")
        out.append("")
    out.append(narrative)
    out.append("")
    out.append(f"## Quantitative summary ({j['ghg_ref']})")
    out.append("")
    out.append("| Scope | tCO2e |")
    out.append("|---|---:|")
    out.append(f"| Scope 1 | {t.scope1} |")
    out.append(f"| Scope 2 (location-based) | {t.scope2_location} |")
    out.append(f"| Scope 3 | {t.scope3} |")
    out.append(f"| **Total (location-based)** | **{t.total_location_based}** |")
    out.append("")
    if t.scope3_by_category:
        out.append("### Scope 3 by category")
        out.append("")
        out.append("| Category | Name | tCO2e |")
        out.append("|---|---|---:|")
        for cat, val in sorted(t.scope3_by_category.items(), key=lambda kv: int(kv[0])):
            out.append(f"| {cat} | {SCOPE3_CATEGORY_NAMES.get(int(cat), 'Other')} | {val} |")
        out.append("")
    out.append("### By activity")
    out.append("")
    out.append("| Activity | Scope | tCO2e |")
    out.append("|---|---|---:|")
    for act, val in sorted(t.by_activity.items(), key=lambda kv: kv[1], reverse=True):
        meta = ACTIVITY_TYPES.get(act, {})
        out.append(f"| {meta.get('label', act)} | {meta.get('scope', '')} | {val} |")
    out.append("")

    out.append("## Methodology and factor citations")
    out.append("")
    used = Counter((e.factor_match.factor.factor_id for e in entries if e.factor_match.factor and e.calculation))
    out.append("| Factor ID | Source | Table reference | Value | Lines |")
    out.append("|---|---|---|---:|---:|")
    seen = set()
    for e in entries:
        fr = e.factor_match.factor
        if fr and fr.factor_id not in seen and e.calculation:
            seen.add(fr.factor_id)
            out.append(f"| {fr.factor_id} | {fr.source} | {fr.table_ref} | {fr.value} kg CO2e/{fr.unit} | {used[fr.factor_id]} |")
    out.append("")

    out.append("## Governance log")
    out.append("")
    out.append("### Control findings")
    out.append("")
    if run.findings:
        out.append("| ID | Severity | Finding | Lines |")
        out.append("|---|---|---|---:|")
        for f in run.findings:
            out.append(f"| {f.check_id} | {f.severity} | {f.title}: {f.detail} | {len(f.line_ids)} |")
    else:
        out.append("No findings.")
    out.append("")
    out.append("### Agent and tool activity (AIMS log)")
    out.append("")
    out.append("| Time | Agent | Mode | Step | Input | Output |")
    out.append("|---|---|---|---|---|---|")
    for l in log:
        out.append(f"| {l.ts} | {l.agent} | {l.mode} | {l.step} | {l.input_summary} | {l.output_summary} |")
    out.append("")

    out.append("## Appendix A — Line-level lineage")
    out.append("")
    out.append("| Line | Source | Activity | Method | Factor | Formula | tCO2e |")
    out.append("|---|---|---|---|---|---|---:|")
    for e in entries:
        if not e.calculation:
            continue
        fr = e.factor_match.factor
        out.append(
            f"| {e.item.line_id} | {e.item.source_file} {e.item.source_ref} | {e.classification.activity_type} | {e.classification.method}"
            f"{(':' + e.classification.rule_id) if e.classification.rule_id else ''} | {fr.factor_id if fr else ''} | {e.calculation.formula} | {e.calculation.t_co2e} |"
        )
    out.append("")
    gaps = [e for e in entries if e.status in ("unmatched_factor", "unclassified", "no_quantity", "unit_error", "duplicate")]
    if gaps:
        out.append("## Appendix B — Data gaps and exclusions (no estimate produced)")
        out.append("")
        out.append("| Line | Source | Status | Reason |")
        out.append("|---|---|---|---|")
        for e in gaps:
            reason = f"duplicate of {e.duplicate_of}" if e.status == "duplicate" else (e.factor_match.reason or e.classification.reason)
            out.append(f"| {e.item.line_id} | {e.item.source_file} {e.item.source_ref} | {e.status} | {reason} |")
        out.append("")
    return "\n".join(out)
